project('upload_client', 'c', version: '0.1.0', subproject_dir: 'lib',
    default_options: [
		'c_std=gnu11',
		'b_lto=false',
		'default_library=static',
		'param:have_fopen=true',
		'param:list_dynamic=true',
		'param:vmem_fram=false',
	],
)

sources = files(
    'src/main.c',
    'src/protobuf/uploadmetadata.pb-c.c',
    'src/session/segments_utils.c',
    'src/session/session_hooks.c',
)

dirs = include_directories(
    'src/include',
    'src/include/vmem',
    'src/include/protobuf',
    'src/include/session',
)

csp_dep = dependency('csp', fallback: ['csp', 'csp_dep'])
m_dep = meson.get_compiler('c').find_library('m', required : false)
dtp_client_dep = dependency('dtp_client', fallback: ['dtp', 'dtp_client_dep'], required: true)
proto_c_dep = dependency('libprotobuf-c', fallback: ['protobuf-c', 'proto_c_dep'])
param_dep = dependency('param', fallback : ['param', 'param_dep']).as_link_whole()
slash_dep = dependency('slash', fallback: ['slash', 'slash_dep'], required: false).partial_dependency(links: false, includes: true)
deps = [csp_dep, dtp_client_dep, proto_c_dep, param_dep, slash_dep, m_dep]

c_args = ['-DHOSTNAME="@0@"'.format(get_option('hostname'))]

executable(
    'upload_client',
    sources,
    include_directories: dirs,
    dependencies: deps,
    install: true,
    c_args: ['-g2', '-O0', '-Wall', '-Wextra'] + c_args,
    link_args: ['-ldl'],
)