/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: protos/uploadmetadata.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "uploadmetadata.pb-c.h"
void   upload_metadata_item__init
                     (UploadMetadataItem         *message)
{
  static const UploadMetadataItem init_value = UPLOAD_METADATA_ITEM__INIT;
  *message = init_value;
}
size_t upload_metadata_item__get_packed_size
                     (const UploadMetadataItem *message)
{
  assert(message->base.descriptor == &upload_metadata_item__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t upload_metadata_item__pack
                     (const UploadMetadataItem *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &upload_metadata_item__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t upload_metadata_item__pack_to_buffer
                     (const UploadMetadataItem *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &upload_metadata_item__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UploadMetadataItem *
       upload_metadata_item__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UploadMetadataItem *)
     protobuf_c_message_unpack (&upload_metadata_item__descriptor,
                                allocator, len, data);
}
void   upload_metadata_item__free_unpacked
                     (UploadMetadataItem *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &upload_metadata_item__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   upload_metadata__init
                     (UploadMetadata         *message)
{
  static const UploadMetadata init_value = UPLOAD_METADATA__INIT;
  *message = init_value;
}
size_t upload_metadata__get_packed_size
                     (const UploadMetadata *message)
{
  assert(message->base.descriptor == &upload_metadata__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t upload_metadata__pack
                     (const UploadMetadata *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &upload_metadata__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t upload_metadata__pack_to_buffer
                     (const UploadMetadata *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &upload_metadata__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UploadMetadata *
       upload_metadata__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UploadMetadata *)
     protobuf_c_message_unpack (&upload_metadata__descriptor,
                                allocator, len, data);
}
void   upload_metadata__free_unpacked
                     (UploadMetadata *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &upload_metadata__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor upload_metadata_item__field_descriptors[5] =
{
  {
    "file_src",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(UploadMetadataItem, file_src),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "file_dest",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(UploadMetadataItem, file_dest),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dtp_server_address",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(UploadMetadataItem, dtp_server_address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "payload_id",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(UploadMetadataItem, payload_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "checksum",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(UploadMetadataItem, checksum),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned upload_metadata_item__field_indices_by_name[] = {
  4,   /* field[4] = checksum */
  2,   /* field[2] = dtp_server_address */
  1,   /* field[1] = file_dest */
  0,   /* field[0] = file_src */
  3,   /* field[3] = payload_id */
};
static const ProtobufCIntRange upload_metadata_item__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor upload_metadata_item__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "UploadMetadataItem",
  "UploadMetadataItem",
  "UploadMetadataItem",
  "",
  sizeof(UploadMetadataItem),
  5,
  upload_metadata_item__field_descriptors,
  upload_metadata_item__field_indices_by_name,
  1,  upload_metadata_item__number_ranges,
  (ProtobufCMessageInit) upload_metadata_item__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor upload_metadata__field_descriptors[1] =
{
  {
    "items",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(UploadMetadata, n_items),
    offsetof(UploadMetadata, items),
    &upload_metadata_item__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned upload_metadata__field_indices_by_name[] = {
  0,   /* field[0] = items */
};
static const ProtobufCIntRange upload_metadata__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor upload_metadata__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "UploadMetadata",
  "UploadMetadata",
  "UploadMetadata",
  "",
  sizeof(UploadMetadata),
  1,
  upload_metadata__field_descriptors,
  upload_metadata__field_indices_by_name,
  1,  upload_metadata__number_ranges,
  (ProtobufCMessageInit) upload_metadata__init,
  NULL,NULL,NULL    /* reserved[123] */
};
