syntax = "proto3";

message UploadMetadataItem {
  // Source file path on the client. Example: "/csh/module.so"
  string file_src = 1;
  
  // Destination file path on the client. Example: "/usr/share/pipeline/module.so"
  string file_dest = 2;

  uint32 dtp_server_address = 3;

  uint32 payload_id = 4;

  // Using fixed32 is efficient for 32-bit checksums like CRC32.
  // For larger hashes like SHA-256, you might use the 'bytes' type instead.
  fixed32 checksum = 5;
}

message UploadMetadata {
    repeated UploadMetadataItem items = 1;
}